---       
- name: add apt repository for latest php packages
  become: yes
  apt_repository:
    repo: ppa:ondrej/php
- name: add apt repository for latest apache2 packages
  become: yes
  apt_repository:
    repo: ppa:ondrej/apache2
- name: install web and db dependencies
  become: yes
  apt:
    name: 
     - php7.3
     - php7.3-common
     - php7.3-mbstring
     - php7.3-xml
     - php7.3-json
     - php7.3-cli
     - php7.3-mysql
     - apache2
     - libapache2-mod-php7.3
     - mysql-server
    update_cache: yes
         